---
game: quake3
engine: idtech3
encoding: latin1
active: false
version: 68

server:
  ping:
    recv: !!binary /////3Bpbmc=
    resp: !!binary /////2Fjaw==
  heartbeat:
    recv: "heartbeat QuakeArena-1\n"
    resp: !!binary /////2Fjaw==
  shutdown:
    recv: !!binary /////3NodXRkb3du
  
client:
  query:
    recv: !!binary cXVlcnk=
    resp: !!binary /////3NlcnZlcnM=

misc:
  server_query: !!binary c3RhdHVzIDIzCg==
  server_print: !!binary cHJpbnQ=
